nav:
    - Introduction: index.md
    - redis-doc-Redis-Cluster-Tutorial: redis-doc-Redis-Cluster-Tutorial
    - redis-doc-Redis-Cluster-Specification: redis-doc-Redis-Cluster-Specification
    - Sharding-strategy: Sharding-strategy
    - Gossip: Gossip
    - Read-the-code: Read-the-code
    - 读写分离: 读写分离